In [18]:
import pandas as pd
import numpy
import scipy
import math
import datetime
import warnings
import os
import shutil
import socket
import platform

In [ ]:
# mostly used libraries
import pandas 
import numpy 
import scipy
import math
import datetime
import warnings

In [ ]:
# numpy is like ocean we will use only limited few functions that is used for Data engineering)
# Mainly used by Data Scientist

In [8]:
import numpy as np  # numerical python

In [ ]:
# it is a general purpose library can be used for any purpose
# Functions: Linear alzebra/ matrix / fourier series
# arrays -> almost like list (performs faster operations)
# IN realtime if data is large list will be having slow performance [numpy --> array] [list --> array]

In [3]:
np.absolute(9)

np.int64(9)

In [4]:
np.absolute(-9.6)

np.float64(9.6)

In [6]:
np.absolute(3.0)

np.float64(3.0)

In [7]:
np.add(5,10)

np.int64(15)

In [ ]:
def add(a,b):
    c = a + b
    print("The Addition of 2 numbers is",c)
def sub(a,b):
    c = a - b
    print("The Subraction of 2 numbers is",c)
def mul(a,b):
    c = a * b
    print("The Multiplication of 2 numbers is",c)   
def div(a,b):
    c = a / b
    print("The Divison of 2 numbers is",c)    

In [12]:
# we can use this numpy for the operational purpose
np.add(5,10)
np.subtract(5,10)
np.multiply(5,10)
np.divide(5,10)

np.float64(0.5)

In [13]:
np.sin(90)

np.float64(0.8939966636005579)

In [15]:
a = [1,2,"Python" , "DE"] 

In [16]:
type(a)

list

In [17]:
b = np.array([1,2,"Python" , "DE"])

In [18]:
type(b)

numpy.ndarray

In [20]:
    print(b)

['1' '2' 'Python' 'DE']


In [21]:
type(b)

numpy.ndarray

In [ ]:
# both list and numpy (array) is collection of elements
# numpy array is used for numerical optimizations (faster)

In [22]:
a[0]

1

In [23]:
b[0]

np.str_('1')

In [ ]:
# accing elements is same but only diff is numpy for larger sets 
# before confirming it is  a list just confirm if it is list or array 

In [25]:
c  = 45.77
np.round(c)

np.float64(46.0)

In [ ]:
# refer Advance_Panda_Quey_200426.ipynb to know how to round off columns

In [26]:
a = [1,2,3,4,5]

In [29]:
type(a)

list

In [27]:
b = np.array([1,2,3,4,5])

In [28]:
type(b)

numpy.ndarray

In [30]:
a[4]

5

In [31]:
b[4]

np.int64(5)

In [32]:
b.ndim # one dimentional

1

In [34]:
c = np.array([[1,2,3],[4,5,6]])

In [37]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
type(c)

numpy.ndarray

In [36]:
c.ndim # two dimentional

2

In [44]:
c[0][1]

np.int64(2)

In [41]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [42]:
d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [43]:
d.ndim # 3 dimentional  

3

In [45]:
d[0][0][0]

np.int64(1)

In [50]:
d[0][2]

array([7, 8, 9])

In [ ]:
# where we are using the numpy for data engineering 

In [53]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\EmployeeDataToClean.csv" , encoding = "ISO-8859-1")

In [54]:
data.head(2)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9.257522e+09,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9.235868e+09,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}


In [ ]:
# without using function / lambda we can change the Maritialstatus from M to male

In [55]:
data['Gender'] = np.where(data['Gender'] == 'M', 'Male', 'Female')

In [56]:
data.head(3)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9.257522e+09,21-02-1986 00:00,M,Male,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9.235868e+09,12-03-1991 00:00,S,Male,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9.416422e+09,21-09-1978 00:00,M,Male,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}


In [57]:
data['MaritalStatus'] = np.where(data['MaritalStatus'] == 'M', 'Married', 'Single')

In [58]:
data.head(3)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9.257522e+09,21-02-1986 00:00,Married,Male,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9.235868e+09,12-03-1991 00:00,Single,Male,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9.416422e+09,21-09-1978 00:00,Married,Male,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}


In [3]:
data1 = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Sample_Store_1.csv", encoding = "ISO-8859-1")

In [4]:
data1.head(5)

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,Sub_Category,ProductName,Sales,Quantity,Discount,Profit
0,2698,CA-2016-145317,18-03-2016,23-03-2016,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
1,6827,CA-2018-118689,02-10-2018,09-10-2018,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2,8154,CA-2019-140151,23-03-2019,25-03-2019,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
3,2624,CA-2019-127180,22-10-2019,24-10-2019,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4,4191,CA-2019-166709,17-11-2019,22-11-2019,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856


In [5]:
df  =data1[["Segment", "Region" , "Category" , "Sales" , "Profit"]]

In [6]:
df

,Segment,Region,Category,Sales,Profit
0,Home Office,South,Technology,22638.480,-1811.0784
1,Corporate,Central,Technology,17499.950,8399.9760
2,Consumer,West,Technology,13999.960,6719.9808
3,Home Office,East,Technology,11199.968,3919.9888
4,Consumer,East,Technology,10499.970,5039.9856
...,...,...,...,...,...
9989,Corporate,Central,Office Supplies,0.876,-1.4016
9990,Consumer,East,Office Supplies,0.852,-0.5964
9991,Corporate,Central,Office Supplies,0.836,-1.3376
9992,Corporate,Central,Office Supplies,0.556,-0.9452


In [7]:
df['Sales_Grp'] = np.where(df['Sales'] < 5000 , 'Bronze', 'Silver') # this condition only have true or false 

NameError: name 'np' is not defined

In [10]:
df['Sales_Grp'] = np.where(df['Sales'] < 5000 , 'Bronze', np.where(df['Sales'] < 10000 , "Silver" ,"Gold"))

C:\Users\DELL\AppData\Local\Temp\ipykernel_1528\972217449.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales_Grp'] = np.where(df['Sales'] < 5000 , 'Bronze', np.where(df['Sales'] < 10000 , "Silver" ,"Gold"))


In [11]:
df .head(5)

,Segment,Region,Category,Sales,Profit,Sales_Grp
0,Home Office,South,Technology,22638.480,-1811.0784,Gold
1,Corporate,Central,Technology,17499.950,8399.9760,Gold
2,Consumer,West,Technology,13999.960,6719.9808,Gold
3,Home Office,East,Technology,11199.968,3919.9888,Gold
4,Consumer,East,Technology,10499.970,5039.9856,Gold


In [12]:
df.groupby("Sales_Grp")[["Segment"]].count()

,Segment
Sales_Grp,
Bronze,9975
Gold,5
Silver,14


In [21]:
df['Sales_Grp'] = np.select([df['Sales'] < 5000 , df['Sales'] < 10000 , df['Sales'] > 10000 ] ,  ["Bronze","Silver","Gold"])

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [20]:
df.head(10)

,Segment,Region,Category,Sales,Profit,Sales_Grp
0,Home Office,South,Technology,22638.480,-1811.0784,Gold
1,Corporate,Central,Technology,17499.950,8399.9760,Gold
2,Consumer,West,Technology,13999.960,6719.9808,Gold
3,Home Office,East,Technology,11199.968,3919.9888,Gold
4,Consumer,East,Technology,10499.970,5039.9856,Gold
5,Consumer,Central,Office Supplies,9892.740,4946.3700,Silver
6,Consumer,Central,Office Supplies,9449.950,4630.4755,Silver
7,Corporate,East,Technology,9099.930,2365.9818,Silver
8,Consumer,South,Technology,8749.950,2799.9840,Silver
9,Consumer,East,Technology,8399.976,1119.9968,Silver


In [22]:
df['Sales_Grp'] = np.select(
    [
        df['Sales'] < 5000,
        (df['Sales'] >= 5000) & (df['Sales'] < 10000),
        df['Sales'] >= 10000
    ],
    [
        "Bronze",
        "Silver",
        "Gold"
    ],
    default="Unknown"
)

C:\Users\DELL\AppData\Local\Temp\ipykernel_1528\2219271748.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sales_Grp'] = np.select(


In [23]:
df.head(5)

,Segment,Region,Category,Sales,Profit,Sales_Grp
0,Home Office,South,Technology,22638.480,-1811.0784,Gold
1,Corporate,Central,Technology,17499.950,8399.9760,Gold
2,Consumer,West,Technology,13999.960,6719.9808,Gold
3,Home Office,East,Technology,11199.968,3919.9888,Gold
4,Consumer,East,Technology,10499.970,5039.9856,Gold


In [ ]:
np.nan # for null values 

In [ ]:
# All the lib are developed by using class